# Generated by Django 2.0.2 on 2019-03-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190326_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon_res',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='addon_res',
            name='r_id',
        ),
        migrations.DeleteModel(
            name='addon_res',
        ),
    ]
